project:
  type: website

website:
  title: "BioFlor"
  site-url: https://thegreatjack.github.io/
  favicon: images/bioflor_logo_V1.png

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

  navbar:
    logo: images/bioflor_logo_V1.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/TheGreatJack
      - icon: twitter
        href: https://twitter.com/AndrewPhill259

format:
  html:
    theme: [sandstone, custom.scss]
    toc: true
    toc-title: Contents
    toc-location: left
